# docker-compose up / docker-compose build

version: '3.9'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - celery_network
  celery_worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DOCKER_NETWORK=True
    command: celery -A tasks worker -l info  # no shared_task decorator
    depends_on:
      - "redis"
    networks:
      - celery_network
    volumes:
      - ./:/usr/src/app
  celery_flower:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: celery -A tasks flower --port=9090 --broker=redis://redis:6379/0 --basic_auth=doit:doit
    environment:
      - DOCKER_NETWORK=True
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - celery_worker
    networks:
      - celery_network

networks:
  celery_network:
